### ISSUE TITLE
Request parameter Settings

### ISSUE THREAD

**Issue by BYR-HZ** [DiMarzioRock7/MS-SincResNet#5]
Dear DiMarzioBian：
     Could you please give me a copy of the parameter Settings of your reproducing paper results？

**Comment by DiMarzioBian** [comment]
Please check the [slides](https://docs.google.com/presentation/d/1p9G7I8BWYW4CqgmkMLI65YDaZfCTBy6v/edit?usp=sharing&ouid=112077339758414489104&rtpof=true&sd=true). This is a course project, I didn't find the detailed result sheet.

**Comment by BYR-HZ** [comment]
Thank you for your share!
